worker_processes  auto;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # Include custom proxy server configuration
    include /usr/local/openresty/nginx/conf/proxy.conf;
}
